engine {
  filesystems {
     oss {
       auth {
         endpoint = "oss-$region-internal.aliyuncs.com"
         access-id = ""
         access-key = ""
       }
     }
  }
}

backend {
  default = EHPC

  providers {
    EHPC {
      actor-factory = "cromwell.backend.impl.ehpc.EhpcBackendLifecycleActorFactory"
      config {
        root = "oss://bucket/"
        region = "$region"
        domain = "ehpcinstant.$region.aliyuncs.com"
        access-id = ""
        access-key = ""
        # security-token = ""

        filesystems {
          oss {
            bucket = "bucket"
            auth {
                endpoint = "oss-$region-internal.aliyuncs.com"
                access-id = ""
                access-key = ""
                # security-token = ""
            }
          }
        }

        default-runtime-attributes {
            failOnStderr: false
            continueOnReturnCode: 0
            # Instant计算服务应用实例ID
            # imageId: "vm镜像ID"
            docker: "crpi-3bfgotc9etmkbfid.cn-shanghai.personal.cr.aliyuncs.com/fdupgx/fastqc:v0.11.9"
            systemDisk: "cloud 40"
            # disks: "local-disk 50 cloud_ssd"
            vpc: "10.0.0.0/16 vpc-uf6n1ualpgdogvgpdb6x2"
            vswitch: "vsw-uf6oqaq6at8m8ty6rwdng"
            # 多个vswitch格式
            # vswitch: ["vsw-2zev0a5ltkgu7z6xxxxxx", "vsw-2zev0a5ltkgu7z6xxxxxx"]
            cpu: 32
            memory: "128GB"
            # Instant调度类型，包含：Standard(标准调度，默认)，Dedicated(专属调度)，Economic(经济调度)
            allocationSpec: "Standard"
            taskSustainable: false
            # 挂载nas，格式  nas挂载点 系统挂载目录
            # mounts: "nas://1734xxxxxx-xxxx.cn-beijing.nas.aliyuncs.com:/ /mnt/"
            # 安全组ID
            # securityGroupId: "sg-2ze1t0n8zyz8k8xxxxxx"
            # 开启本地计算
            # localization: true
            # 通用型: General（默认） 性能型: Performance  该配置经济调度专属
            # level: "Performance"
            # 标签
            # instantTag: ["key1=val1", "key2=key2"]
            # 运行环境的实例规格       限制：最多5组，仅支持调度策略为Standard，算力等级为General
            # instanceTypes: ["ecs.xxxx.8xlarge"]
            # 设定挂载点内文件/文件夹的权限掩码 详见oss官档：https://help.aliyun.com/zh/oss/developer-reference/mount-point-permission-configuration?spm=a2c4g.11186623.0.i19
            ossMountUmask: "000"
        }
      }
    }
  }
}
